### ISSUE TITLE
Draft 1.0 of CPG Roadmap

### ISSUE THREAD

**Issue by musingvirtual** [mozilla/diversity#151]
## Objective Goal: 
We have identified , prioritized and organized a series of tasks by quarter - that will on completion result in effective response to CPG reports in Mozilla's communities in end of 2018/2019.

## Related documents and links 
* [Roadmap v 2](https://docs.google.com/document/d/13sPUnEWlX9K_eA_Jk5zK1yWJZZRKzSZaBniYS09e0MI/edit#)
* [Roadmap v 1](https://docs.google.com/document/d/1u-S_Ob_FE6EKG_fi_K62kD_IQ1noQpHHJ399DXlKy2E/edit#)

- [x] Under each milestone, and ‘meta’ and problems, and proposed goals under that problem. 
- [x]  Review, and prioritize (Emma & Kate) 
- [x]  Identify for each P1, P2 - ‘What Success Looks like’ (Emma & Kate)  (Not Started)
- [x] Default P1’s for Q2  are Systems work we’re already doing, and answering ‘What is Scale’.
- [x] Assign by quarter.
- [ ] Identify possible dependencies  .
- [ ] Sign-off approval from Lucy & George .

## Related Issues
[Reference meta issues and past issues] #144

**Comment by musingvirtual** [comment]
Have scheduled time on Monday to review Emma's work on the roadmap.
