### ISSUE TITLE
3 systems demos have been scheduled (and are underway, or completed) 

### ISSUE THREAD

**Issue by emmairwin** [mozilla/diversity#167]
## Objective Goal: 
Informed by user stories, systems requirements and in consultation with stakeholders, we have started research into the best Hotline system for CPG community response.

### Roadmap & Deadlines 

- [x] Kate and Emma build user stories doc (Tower of London Sprint)

- [x] Kate and Emma do demo with Convercent (May 30th)

- [x] Emma generate alignment with Henrik & George (June 1)

- [x] Kate to reach out to a number of contacts at relevant organizations to see if anyone has built or is building something. (June 4)

- [x] Kate to reach out within Mozilla to people who might have any knowledge of problem space (June 4)

- [x] Kate to do demo with Mogul's Safety @ Work (June 6)

- [x] Kate to do demo with Callisto (June 15)

- [x] Kate to write up doc summarizing demos and any other promising information, plus suggested roadmap for remainder of June in order to make best use of time with Arielle (June 11th)

- [x] Kate to work with Arielle at All-Hands to find out what she knows (June 11th)

## Related Issues
#156

**Comment by musingvirtual** [comment]
Have scheduled some time on Monday to bash out a plan and approximate timeline for this work, will send it for your review when it is done.

**Comment by musingvirtual** [comment]
Emma, I added a rough draft of a timeline at least for this sprint, I'll figure out the next sprint after meeting with Arielle.

**Comment by emmairwin** [comment]
Looks good!

**Comment by emmairwin** [comment]
This looks good!  I pinged you to add your progress to today;s meeting dashboard.

**Comment by musingvirtual** [comment]
Closing this one, moving further work to new task for Hazel sprint.

**Comment by emmairwin** [comment]
Hey Kate - can you update on where you are before closing this?   thank you!

**Comment by musingvirtual** [comment]
That was a doc to prepare for my meeting with Arielle. It is not up to date with the two demos I had last week or really ready for another person to use.  I had intended to make a production ready document initially but there was not time because I had casework.  Documentation and roadmaps that are ready to share will be the work of the next sprint.
