### ISSUE TITLE
CPG Systems Project - Milestone 1 Part 2 & Milestone 2

### ISSUE THREAD

**Issue by musingvirtual** [mozilla/diversity#201]
## Objective Goal: 
Working towards milestones 1 & 2 - contract signature (July 31st) & security/data privacy audits (Aug 10th)

## Related documents and links 
* (https://docs.google.com/spreadsheets/d/1Apc-XTYyUo518CeCQDPTBv3lsQYeJ-YMXEj8oA-ttK4/edit#gid=0)
* (https://docs.google.com/spreadsheets/d/1UtqLJlUmXyRd_b4YmrXJcv4joyYsn8y-Ma3tK5Afzx4/edit#gid=0)

## Item list:
- [x] Continue chasing sign-off with stakeholders (R: @musingvirtual - due July 31st)
- [x] Continue coordinating between vendor and procurement/CASA team (R: @musingvirtual - due July 31st)
- [X] Architect Permissions & Roles Scheme (R: @musingvirtual - draft July 23rd, may need follow up questions with the vendor or with legal.) 
- [x] Speak with Rina about proposed UX commitment to this project (R @musingvirtual, scheduled July 24th)
- [x] Kick off collaboration with Alicia Gray (R @musingvirtual, depends on completing roles scheme - commence July 24th).
- [ ] Meet with Arielle regarding access groups in Mozillians (R @musingvirtual - deferred due to not having needed information from vendor, moving this task to another part of the project timeline because it's become apparent that we won't be able to answer the needed questions for a while)
- [ ] Begin drafting reporting intake form (R @musingvirtual - began draft this week, still working, moving to next sprint)

## Related Issues
#182 #199

**Comment by musingvirtual** [comment]
I have made progress towards sign-off and continued to coordinate with the vendor. Both of these tasks are ongoing next week as well.

I updated this task to add a few more items which I will carry into the next two weeks.

**Comment by musingvirtual** [comment]
Working with Alicia Gray, have reached out to Arielle to see what info she will need to scope Mozillians Groups, have sent Rina information.

**Comment by musingvirtual** [comment]
Closing this and reflecting tasks in new epic.
