### ISSUE TITLE
All research required for Devtools experiment are completed, and insights shared

### ISSUE THREAD

**Issue by emmairwin** [mozilla/diversity#205]
## Objective Goal: 
All quantitative, and qualitative research goals have been documented, and completed.

## Related documents and links 
* [Internal Charter](https://docs.google.com/document/d/1fZcWKvvA0s9DnXxov4K0FNPMTuNwEOhtKmvIoHpg8p8/edit)

## Item list:
- [ ] Devtools contributor interviews are completed(R: @emmairwin)
- [ ] External interviews are identified,  and scheduled (R: @emmairwin)
- [ ] External interviews are completed (R: @emmairwin)
- [ ] Insights and early recommendations shared (R: @emmairwin)

## Related Issues 
[Reference meta issues and past issues] #
