### ISSUE TITLE
Leveraging CHAOSS D&I gial-metrics, a Kibana prototype is created, and shared on the OI call (and beyond)

### ISSUE THREAD

**Issue by emmairwin** [mozilla/diversity#206]
## Objective Goal: 
We have an early prototype of what D&I metrics that matter 

## Item list:
- [x]  Setup call with Daniel to answer questions/speed up knowledge (Due-Date August 2nd R: @emmairwin) 
- [x]  Find host for solution (Due-Date August 6th:   R: @emmairwin @akshitac8 )
- [x]  Add data dummy-set, to make visualizations look more realistic (Due-Date August 11th:  R: @akshitac8 @emmairwin)
- [x]  Create a presentation/practice demo Due-Date August 14th:  (R: @akshitac8 , @emmairwin)
- [x]  Demo on CHAOSS D&I Call (next call) (Due-Date TBD R: @akshitac8  )

**Comment by emmairwin** [comment]
External hosting is now optional task
