### ISSUE TITLE
Hotline System Milestones for Form, and Data privacy are completed

### ISSUE THREAD

**Issue by emmairwin** [mozilla/diversity#207]
## Objective Goal: 
We've completed our data privacy policy, established the fields for our reporting form, and established a timeline for technical implementation.

## Item list:
- [x] Kickoff call with vendor to agree on time-line (Due-Date: August 10th R: @musingvirtual )
- [x] Data policy is signed-off (Due-Date: August 24th R: @musingvirtual )
- [ ] Draft of reporting form delivered to Convercent (Due-Date: August 24th R: @musingvirtual)
- [ ] Timeline for SSO integration and QA work agreed with ParSys team (Due-Date August 28th R: @musingvirtual)

**Comment by musingvirtual** [comment]
The data policy has been signed off by Alicia, but she wants to approve where it appears in the reporting form so I've added this to my critical path.  There is an additional activity around flow for GDPR requests which she raised that we are completing this week.

I am very concerned about delivering the reporting form at this point because I've found out that I won't have access to the system until Thursday, as we discussed in the morning meeting today. I'm asking the vendor for an example of another client's reporting form so that I can paper prototype the reporting form and circulate that.
