### ISSUE TITLE
A First Draft of the CPG playbook is created, and shared with key stakeholders for feedback

### ISSUE THREAD

**Issue by emmairwin** [mozilla/diversity#208]
## Objective Goal: 
We have a first draft to interact with and iterate.

## Item list:
- [x] First outline completed (Due-Date: Aug 14th R: @musingvirtual )
- [ ] Draft completed  (Due-Date: Aug 26th R @musingvirtual:)
- [ ] Shared with key stakelhoders (Due-Date: Aug 27th R: @musingvirtual )

**Comment by musingvirtual** [comment]
Relieved to have one project here that has no external delays or yaks to shave!
