### ISSUE TITLE
We have an early implementation for time  tracking and providing reports of time spent consulting and responding to CPG Cases

### ISSUE THREAD

**Issue by emmairwin** [mozilla/diversity#209]
## Objective Goal: 
We are tracking and providing reports of time spent consulting and responding to CPG Cases

## Item list:
- [x]  Identify which attributes we will track for cases, and for consultation (Due-Date: August 10th R: @musingvirtual )
- [ ]  Tracking is setup, and being implemented as part of all case and consultation work (Due-Date: August 24th R: @musingvirtual  )
- [x]  Reports added to K&G update (weekly? Monthly?) (Due-Date: Week of August 26th R: @musingvirtual )
- [ ]  Investigate multiple-people time tracking  (Due-Date: Aug 24th @musingvirtual. )

**Comment by musingvirtual** [comment]
There are also no issues here and this work is on schedule to deliver by the end of the sprint!
