### ISSUE TITLE
Based on survey results,  have shared insights into the question 'What is Scale' - and are beginning to apply to systems implementation planning

### ISSUE THREAD

**Issue by emmairwin** [mozilla/diversity#210]
## Item list:
- [x] Clarify privacy policy for external CPG data  (R: @musingvirtual )
- [x] Meet with Emma H, to review current triage materials and if there are existing Bugzilla triage processes we can leverage (@mussingvirtual) 
- [ ] Synthesize findings from surveys into summary, and share with CB team/async (R : @musingvirtual 
- [ ] Blog post written  (R: @emmairwin )

**Comment by musingvirtual** [comment]
I haven't started this but I'm sort of wondering if I can fit some work on this in later this week. Let me do some planning a little later today/early tomorrow and let you know.

**Comment by emmairwin** [comment]
Hi @musingvirtual can you please share the results document with me?  Thanks!
