### ISSUE TITLE
Devtools research is moving forward with approved goals, and alignment with stakeholders 

### ISSUE THREAD

**Issue by emmairwin** [mozilla/diversity#211]
## Objective Goal: 
Detailed description on what should happen to conside this a success.

## Related documents and links 
* [Links here](/thelink)

## Item list:
- [x] Kickoff for devtools w/ Susy & Krishna (Due Date: August 10th R: @emmairwin )
- [x] Devtools team is updated with outcome of kickoff meeting (Due Date: August 17th  R: @emmairwin & Susy)
- [ ]  I can summarize what the impact of P1, P2 are in the devtools/debugger
- [x] 4 Interviews are scheduled for Devtools research (Due Date: August 10th R: @emmairwin)
- [ ] A plan for user research, including identified volunteer participants is completed with planning underway (Due Date: August 24th R: @emmairwin)

## Related Issues
[Reference meta issues and past issues] #

**Comment by emmairwin** [comment]
Interviews are underway
I installed the devtools environment, played around with code, and learned what support docs exist.  next to write the script.  

Scheduling people underway ( I have 5 volunteers for user testing)
