### ISSUE TITLE
D&I Strategy for MOSS is underway according to approved timeline

### ISSUE THREAD

**Issue by emmairwin** [mozilla/diversity#212]
## Item list:
- [x]  Goals and strategy are reviewed by MOSS team, and updated based on that feedback Due (August 17th R: @emmairwin)
- [ ] Consultation with legal on diversity fields, and CPG api
- [ ] Application funnel, and grantee baseline measurements underway   (Due Date: August 17th R: @emmairwin)
- [ ]  Review with Mitchell scheduled (R: @emmairwin)
