### ISSUE TITLE
We've interviewed 3 big open source projects about their D&I goals, and scheduled a D&I call with at least one on this topic

### ISSUE THREAD

**Issue by emmairwin** [mozilla/diversity#213]
## Item list:
- [x] Write introduction/ask content (due-date: August 8, R: @emmairwin)
- [ ] Reach out to 5 big open source projects (due date August 10th R: @emmairwin)
- [ ] Completed at least 3 interviews (due date Aug 31: R: @emmairwin)
- [ ] D&I call scheduled (Due Date August 27th R: @emmairwin )
- [ ]  Initial draft of the D&I Network is created  (Due Date August 27th R: @emmairwin )
